### PR TITLE
style/remove-notused-file

### PR DESCRIPTION
**Pull request by Gunbam27**
### 각자 작성한 파일 확인 후 체크표시 -> 모든 리스트 체크 이후 MERGE
MODEL
- [ ] domain - model - detail - course
- [ ] domain - model - detail - culture_location
- [ ] domain - model - detail - festival
- [ ] domain - model - detail - leports
- [ ] domain - model - detail - lodgement
- [ ] domain - model - detail - restaurant
- [ ] domain - model - detail - shopping
- [ ] domain - model - detail - tourist_spot

MAPPER
- [x] data - mapper -content_detail_mapper.dart
- [x] data - mapper -content_detail_info_mapper.dart

REPOSITORY
- [x] domain - repository -unified_detail_repository.dart
- [x] data - repository_impl -unified_detail_repositorty_impl.dart

PRESENTAIION
- [x] presentaion - detail_screen (빈폴더)
- [ ] presentaion - detail - contents_detail - contents_detail_view_model.dart
- [ ] presentaion - detail - contents_detail - contents_detail_screen.dart
- [ ] presentaion - detail - contents_detail - lodgement_detail_view.dart
- [ ] presentaion - detail - contents_detail - restaurant_detail_view.dart
- [ ] presentaion - detail - contents_detail - shopping_detail_view.dart
- [x] presentaion - detail - contents_detail - culture_location_view_model.dart
- [x] presentaion - detail - contents_detail - culture_location_screen.dart

### MODIFIED FILE LIST
- [x] domain - repository - tour_info_repository.dart
- [x] data - repository_impl - tour_info_repository_impl.dart

제거된 파일 임포트 제거하였습니다.

### CODE REVIEW

**Comment by chojja7188** [comment]
6000개 삭제라니,, 귀찮은 작업이셨을텐데 고생하셨습니다~!! 👍👍
Mapper는 삭제해도 무관한 것으로 확인했습니다!

**Comment by itbebop** [comment]
와 고생 많으셨습니다
tour_info_repository
tour_info_repository_impl.dart 필요없는 부분 삭제 등
수정하신 것 확인했습니다

**Comment by jungeun272** [comment]
정리해주셔서 감사합니다 :)

**Comment by yujiyeong** [comment]
우와 너무 고생하셨습니다!!!! 어려운 작업 해주셔서 감사합니다!

**Pull request merged**
