### PR TITLE
Feat/unified data format

### PR DESCRIPTION
**Pull request by Gunbam27**
모델
unified_detail
unified_info

mapper
unitied_detail_mapper
unitied_info_mapper

repository
unitied_detail_repository
unitied_detail_repository_impl

View
detail_screen
detail_screen_view_model

### CODE REVIEW

**Comment by chojja7188** [comment]
다 모아놓은거 좋은 것 같습니다~ 고생하셨습니다 👍👍

**Comment by itbebop** [comment]
크으.. 벌써 리팩토링까지 훌륭하십니다 👍👍👍

**Comment by jungeun272** [comment]
LGTM bb

**Comment by frihett** [comment]
유용할 것 같습니다 good

**Pull request merged**
